### ISSUE TITLE
Rename parameter prefix in plugins/postprocessing_commands/*/*.edi to reduce diff between edi-pi and edi-imx

### ISSUE THREAD

**Issue by ghost** [lueschem/edi-cl#1]
edi-imx uses `{{ imx_timestamp }}` while edi-pi uses `{{rpi_timestamp}`
The prefix could be more generic such that we don't have to modify the files in instances of EDI.

Proposal:
`imx_timestamp` -> `postprocess_timestamp_output`
`imx_mender_artifact` -> `postprocess_mender_output`

This might help move it upstream into EDI in the future...

**Comment by lueschem** [comment]
This is a very good idea. As soon as we get rid of project specific prefixes different projects also becomes easier to compare.
As such we should also get rid of folders that contain project specific prefixes.

About your proposal: I would prefer slightly shorter names (e.g. we could get rid of the `_output` postfix). With regards to the prefix: Basically we do not need a prefix. However, the prefix acts like a namespace and helps to avoid naming clashes. What about using `pp_` as the prefix? Then (with some additional cleanup) it might look like this:

imx_timestamp -> pp_timestamp
imx_rootfs -> pp_rootfs
imx_image -> pp_full_image
imx_partition_image -> pp_rootfs_image
imx_bmap -> pp_full_image_blockmap
imx_mender_artifact -> pp_mender_artifact
imx_documentation -> pp_documentation

What do you think?

**Comment by ghost** [comment]
I like it. I agree that both a short prefix, and the name clash avoidance, is a Good Thing.

**Comment by ghost** [comment]
With respect to "get rid of folders that contain project specific prefixes": are you thinking of rpi_base vs imx_base? At least, that is one such candidate.

**Comment by lueschem** [comment]
Yes, correct. rpi_base and imx_base could become base_system.

**Comment by ghost** [comment]
If rpi_base and imx_base is renamed to base_system, then there is a potential issue: two different version of `base_system`; one in EDI provided playbook, and the local. Let's skip the rpi_base and imx_base in this issue to keep it focused.

**Comment by lueschem** [comment]
Looks good - the diff between edi-pi and edi-imx got quite a bit smaller. Many thanks!

**Comment by ghost** [comment]
Glad I could help. Now I agree, it would be nice to have the folders cleaned of the rpi and imx as well. I'm unsure about which strategy to use.
