### ISSUE TITLE
Switch from dos to gpt partition table

### ISSUE THREAD

**Issue by lueschem** [lueschem/edi-cl#15]
To get rid of some legacy it could make sense to switch from the dos partition table to the gpt partition table.

Things to consider:

- gpt has a secondary partition table at the end of the disk.
- edi-resize-rootfs and rootfs2image need to take this into account.
- sfdisk needs to be replaced by sgdisk.
- An old edi-resize-rootfs script might throw errors when trying to resize a gpt disk. Therefore a new image type might make sense.

**Comment by ghost** [comment]
Nice!
