### ISSUE TITLE
VAR-SOM-6UL support.

### ISSUE THREAD

**Issue by ghost** [lueschem/edi-cl#2]
See http://variwiki.com/index.php?title=VAR-SOM-6UL for ideas.

**Comment by vw-scanomat** [comment]
I'm working on this  https://github.com/vw-scanomat/edi-imx/tree/feature/imx6ul

**Comment by ghost** [comment]
I'm working on this https://github.com/vw-scanomat/edi-imx/tree/feature/var-som-imx6
